[project]
name = "langchain-academy"
version = "0.1.0"
description = "Lang Graph course."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-openai>=0.3.30",
    "langgraph>=0.6.6",
    "langgraph-cli[inmem]>=0.3.7",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.9",
]
